//enum __declspec(uuid("c8679e0a-1c67-3a20-8645-0d930f529031"))
ENUM!{enum FieldAttributes {
    FieldAttributes_FieldAccessMask = 7,
    FieldAttributes_PrivateScope = 0,
    FieldAttributes_Private = 1,
    FieldAttributes_FamANDAssem = 2,
    FieldAttributes_Assembly = 3,
    FieldAttributes_Family = 4,
    FieldAttributes_FamORAssem = 5,
    FieldAttributes_Public = 6,
    FieldAttributes_Static = 16,
    FieldAttributes_InitOnly = 32,
    FieldAttributes_Literal = 64,
    FieldAttributes_NotSerialized = 128,
    FieldAttributes_SpecialName = 512,
    FieldAttributes_PinvokeImpl = 8192,
    FieldAttributes_ReservedMask = 38144,
    FieldAttributes_RTSpecialName = 1024,
    FieldAttributes_HasFieldMarshal = 4096,
    FieldAttributes_HasDefault = 32768,
    FieldAttributes_HasFieldRVA = 256,
}}