//enum __declspec(uuid("299e2a7d-6551-3ed1-b4a0-a51cb56eefe7"))
ENUM!{enum UnicodeCategory
{
    UnicodeCategory_UppercaseLetter = 0,
    UnicodeCategory_LowercaseLetter = 1,
    UnicodeCategory_TitlecaseLetter = 2,
    UnicodeCategory_ModifierLetter = 3,
    UnicodeCategory_OtherLetter = 4,
    UnicodeCategory_NonSpacingMark = 5,
    UnicodeCategory_SpacingCombiningMark = 6,
    UnicodeCategory_EnclosingMark = 7,
    UnicodeCategory_DecimalDigitNumber = 8,
    UnicodeCategory_LetterNumber = 9,
    UnicodeCategory_OtherNumber = 10,
    UnicodeCategory_SpaceSeparator = 11,
    UnicodeCategory_LineSeparator = 12,
    UnicodeCategory_ParagraphSeparator = 13,
    UnicodeCategory_Control = 14,
    UnicodeCategory_Format = 15,
    UnicodeCategory_Surrogate = 16,
    UnicodeCategory_PrivateUse = 17,
    UnicodeCategory_ConnectorPunctuation = 18,
    UnicodeCategory_DashPunctuation = 19,
    UnicodeCategory_OpenPunctuation = 20,
    UnicodeCategory_ClosePunctuation = 21,
    UnicodeCategory_InitialQuotePunctuation = 22,
    UnicodeCategory_FinalQuotePunctuation = 23,
    UnicodeCategory_OtherPunctuation = 24,
    UnicodeCategory_MathSymbol = 25,
    UnicodeCategory_CurrencySymbol = 26,
    UnicodeCategory_ModifierSymbol = 27,
    UnicodeCategory_OtherSymbol = 28,
    UnicodeCategory_OtherNotAssigned = 29,
}}